baseurl: "/"
title: Leruaite Econ么mico
theme: ghostwriter
languageCode: pt
copyright: 2013-2020 Leruaite Econ么mico
disqusShortname: XXX
googleAnalytics: XXX
pygmentsUseClasses: true
pygmentsCodefences: true

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 2

privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: false

author:
  name: Marcelino Guerra
  profile: "guerramarcelino.github.io"

taxonomies:
  tag: tags

params:
  mainSections:
    - post
  intro: true
  headline: Leruaite Econ么mico
  description: Este blog respeita a teoria econ么mica
  github: "https://github.com/regressoesespurias"
  #gitlab: "https://gitlab.com/XXX"
  #linkedin: "https://linkedin.com/in/XXX/"
  twitter: "https://twitter.com/leruaite"
  #stackoverflow: "https://stackoverflow.com/users/XXX/YYY"
  facebook: "https://www.facebook.com/leruaiteeconomico"
  email: leruaiteeconomico@gmail.com
  opengraph: true
  shareTwitter: true
  rss: true
  shareFacebook: true
  shareLinkedIn: false
  dateFormat: "2 Jan, 2006"
  exponeaJsUrl: ""
  exponeaTarget: ""
  exponeaToken: ""
  exponeaTrackVisits: false
  readingTime: true
  readingTimeText: "Estimated reading time:"
  fathomUrl: ""
  fathomSiteId: ""
  # If you want to use plausible(https://plausible.io) for analytics, add this section
  plausibleAnalytics:
    domain: ""
    # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
    serverURL: ""

permalinks:
  post: "/:year/:month/:day/:filename/"

menu:
  main:
    - name: Blog
      url: /
      weight: 1
    - name: Projects
      url: /project/
      weight: 2
    - name: Contact
      url: /page/contact/
      weight: 3
    - name: About
      url: /page/about/
      weight: 4
